name: job_application
description: A feature package for managing job applications.
version: 0.0.1
publish_to: none

resolution: workspace

environment:
  sdk: ^3.10.0

dependencies:
  cloud_firestore: ^6.1.0
  equatable: ^2.0.0
  flutter:
    sdk: flutter
  flutter_core:
    path: ../flutter_core
  freezed_annotation: ^3.1.0
  get_it: ^9.2.0
  json_annotation: ^4.9.0
  uuid: ^4.0.0

dev_dependencies:
  build_runner: ^2.10.4
  flutter_test:
    sdk: flutter
  freezed: ^3.2.3
  json_serializable: ^6.0.0
  mockito: ^5.6.1
