name: job_application_tracker
description: "A new Flutter project."
publish_to: "none"
version: 0.1.0

environment:
  sdk: ^3.9.0

resolution: workspace

dependencies:
  authentication:
    path: ../../packages/authentication
  firebase_auth: ^6.1.2
  firebase_core: ^4.2.1
  firebase_messaging: ^16.0.4
  firebase_ui_auth: ^3.0.1
  flutter:
    sdk: flutter
  flutter_bloc: ^9.1.1
  flutter_core:
    path: ../../packages/flutter_core
  flutter_local_notifications: ^19.5.0
  flutter_localizations:
    sdk: flutter
  freezed_annotation: ^3.1.0
  get_it: ^9.1.0
  go_router: ^17.0.0
  intl: any
  notification:
    path: ../../packages/notification
  shimmer: ^3.0.0

dev_dependencies:
  flutter_lints: ^6.0.0
  flutter_test:
    sdk: flutter
  freezed: ^3.2.3

flutter:
  uses-material-design: true
  generate: true
