name: job_application_tracker
description: "A new Flutter project."
publish_to: "none"
version: 0.1.0

environment:
  sdk: ^3.9.0

resolution: workspace

dependencies:
  add_2_calendar: ^3.0.1
  authentication:
    path: ../../packages/authentication
  currency_picker: ^2.0.21
  firebase_auth: ^6.1.2
  firebase_core: ^4.2.1
  firebase_messaging: ^16.0.4
  firebase_ui_auth: ^3.0.1
  flutter:
    sdk: flutter
  flutter_bloc: ^9.1.1
  flutter_core:
    path: ../../packages/flutter_core
  flutter_form_builder: ^10.2.0
  flutter_local_notifications: ^19.5.0
  flutter_localizations:
    sdk: flutter
  form_builder_validators: ^11.2.0
  freezed_annotation: ^3.1.0
  get_it: ^9.1.0
  go_router: ^17.0.0
  intl: any
  job_application:
    path: ../../packages/job_application
  json_annotation: ^4.9.0
  location_tracking:
    path: ../../packages/location_tracking
  notification:
    path: ../../packages/notification
  percent_indicator: ^4.2.5
  shimmer: ^3.0.0

dev_dependencies:
  bloc_test: ^10.0.0
  build_runner: ^2.10.4
  flutter_lints: ^6.0.0
  flutter_test:
    sdk: flutter
  freezed: ^3.2.3
  json_serializable: ^6.11.2
  mockito: ^5.6.1

flutter:
  uses-material-design: true
  generate: true
