name: job_application_tracker
description: "A new Flutter project."
publish_to: "none"
version: 0.1.0

environment:
  sdk: ^3.9.0

resolution: workspace

dependencies:
  firebase_auth: ^6.1.2
  firebase_authentication:
    path: ../../packages/firebase_authentication
  firebase_core: ^4.2.1
  firebase_ui_auth: ^3.0.1
  flutter:
    sdk: flutter
  flutter_bloc: ^9.1.1
  flutter_core:
    path: ../../packages/flutter_core
  flutter_localizations:
    sdk: flutter
  freezed_annotation: ^3.1.0
  get_it: ^9.1.0
  go_router: ^17.0.0
  intl: any

dev_dependencies:
  flutter_lints: ^5.0.0
  flutter_test:
    sdk: flutter
  freezed: ^3.2.3

flutter:
  uses-material-design: true
  generate: true
