name: budget_core
description: Core package for budget tracking with domain entities and repository contracts.
version: 0.0.1
publish_to: none
resolution: workspace

environment:
  sdk: ^3.9.0

dependencies:
  equatable: ^2.0.7
  flutter:
    sdk: flutter
  flutter_core:
  freezed_annotation: ^3.0.0
  get_it: ^9.0.5
  json_annotation: ^4.9.0
  path: ^1.9.1
  sqflite: ^2.4.2
  uuid: ^4.5.1

dev_dependencies:
  build_runner: ^2.4.15
  flutter_test:
    sdk: flutter
  freezed: ^3.0.6
  json_serializable: ^6.9.5
  mockito: ^5.4.6
  sqflite_common_ffi: ^2.3.4+4
  very_good_analysis: ^10.0.0
