name: notification
description: A reusable package for handling Firebase Cloud Messaging.
version: 1.0.0
publish_to: "none"

resolution: workspace

environment:
  sdk: ^3.9.0
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter
  firebase_messaging: ^16.0.4
  flutter_core:
    path: ../flutter_core
  get_it: ^9.1.0
  equatable: ^2.0.5
  fpdart: ^1.1.0

dev_dependencies:
  build_runner: ^2.4.8
  flutter_test:
    sdk: flutter
  mockito: ^5.4.4
  flutter_lints: ^6.0.0
